version: '3'

services:
  database:
    build: ./database
    restart: always
    container_name: database
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test0
    # ports:
    #   - "3306:3306"
    # expose:
    #   - 3306
    networks:
      - network_sql

  test:
    build:
      dockerfile: dockerfile
      context: ./python
    container_name: test
    networks:
      - network_sql
    depends_on:
      - database
    environment:
      DB_HOST: database  # Use the name of the MySQL container as the host
      DB_USER: root
      DB_PASSWORD: 123456
      DB_DATABASE: test0
networks:
  network_sql:






