FROM alpine:3.14

ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 py3-pip && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip

RUN pip3 install pymysql
# Define environment variable defaults
ENV DB_HOST=localhost \
    DB_USER=root \
    DB_PASSWORD= \
    DB_DATABASE=mydatabase
COPY . /test
WORKDIR /test

# EXPOSE 80
# 같은 네트워크로 바인딩 했기 때문에 포트 개방 안해도 됨

CMD ["sh", "-c", "sleep 20 && python test.py"]
